In [144]:
%%writefile PlateParser.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
def file2dfs(fname):
    with open(fname,'r') as f:
        mcount = -1
        buf = ''
        lst = []
        header = [None]*2
        OUTPUT = []
        while True:
            line = next(f,'Read')
    #     for line in f:
    #         buf += []        
            if line.startswith('Read'):
                newheader = [line, next(f,None)]
                if newheader[0] != header[0] or newheader[1] is None:
                    print 'newheader is：',newheader
                    if lst:
                        name = header[0].strip()
                        df = pd.concat(lst,axis=0)
                        OUTPUT += [(name,df)]
                    lst = []
                    if newheader[1] is None:
                        break
                header = newheader
                mcount += 1
                if mcount >= 1:                
    #                 break
                    time = timePTN.findall(''.join(header) )[0]
                    dfc = buffer2data(buf)
                    if mcount == 1:
                        col = paste0(dfc.iloc[:,:2].values.T)
                    dfc = dfc[['value']].T;
                    dfc.columns = col
                    dfc = dfc.set_index([[time]])
                    lst += [dfc]
                    buf = ''
    #                 if mcount == 5:
    #                     dfc = pd.concat(lst,axis=0)
    #                     break
            else:
                if not buf:
                    buf = line
                else:
                    buf = '%s\n%s' %(buf, line)
    return OUTPUT

def buffer2data(buf):
    df = pd.read_table(StringIO.StringIO(buf))
    dfc = df.iloc[:,:12]
    dfc.columns = np.arange(0,12)
    # .reset_index()
    # dfc

    dfc= pd.melt(dfc.reset_index(), 
                id_vars='index', 
                value_vars=list(dfc.columns), # list of days of the week
                value_name='value',
           )
    return dfc

def paste0(ss,sep=None,na_rep=None):
    '''Analogy to R paste0
    '''
    if sep is None:
        sep=''
    res = [sep.join(str(s) for s in x) for x in zip(*ss)]
    res = pd.Series(res)
    return res

import argparse
import pandas as pd
import numpy as np
import StringIO
import re
timePTN = re.compile('\((.*)\)')

parser = argparse.ArgumentParser()
parser.add_argument('filename',nargs='+',help='raw txt file containing 96 well data')

if __name__=='__main__':
    args =  parser.parse_args()
    OUTPUT = file2dfs(args.filename[0])
    for k,df in OUTPUT:
        k = k.replace(' ','_').replace('/','-')
        outname = '%s.csv'%k
        print '[OUTPUT] to %s' % outname
        df.to_csv(outname,index_label = 'time')

Overwriting plateParser.py

In [145]:
%%bash
chmod +x *.py
./plateParser.py *.txt

newheader is： ['Read 1:600\r\r\n', 'Kinetic read 1 (0:00:12)\r\r\n']
newheader is： ['Read 2:480/20,520/20\r\r\n', 'Kinetic read 1 (0:00:43)\r\r\n']
newheader is： ['Read 2:480/20,520/20[2]\r\r\n', 'Kinetic read 1 (0:01:27)\r\r\n']
newheader is： ['Read', None]
[OUTPUT] to Read_1:600.csv
[OUTPUT] to Read_2:480-20,520-20.csv
[OUTPUT] to Read_2:480-20,520-20[2].csv

'0:15:12'

In [64]:
header

'Read 1:600\r\r\nKinetic read 2 (0:15:12)\r\r\n'

In [60]:
# print header
# print 'buf'
# print buf

buf

In [58]:

paste0(dfc.iloc[:,:2].values.T)

0      A0
1      B0
2      C0
3      D0
4      E0
5      F0
6      G0
7      H0
8      A1
9      B1
10     C1
11     D1
12     E1
13     F1
14     G1
15     H1
16     A2
17     B2
18     C2
19     D2
20     E2
21     F2
22     G2
23     H2
24     A3
25     B3
26     C3
27     D3
28     E3
29     F3
     ...
66     C8
67     D8
68     E8
69     F8
70     G8
71     H8
72     A9
73     B9
74     C9
75     D9
76     E9
77     F9
78     G9
79     H9
80    A10
81    B10
82    C10
83    D10
84    E10
85    F10
86    G10
87    H10
88    A11
89    B11
90    C11
91    D11
92    E11
93    F11
94    G11
95    H11
Length: 96, dtype: object

In [42]:

# df.set_index(df.columns[0],inplace=True)
# df
# df.columns = np.arange(12)

   index variable  value
0      A        0  0.126
1      B        0  0.121
2      C        0  0.120
3      D        0  0.105
4      E        0  0.103
5      F        0  0.103
6      G        0  0.104
7      H        0  0.103
8      A        1  0.123
9      B        1  0.123
10     C        1  0.127
11     D        1  0.110
12     E        1  0.112
13     F        1  0.107
14     G        1  0.107
15     H        1  0.105
16     A        2  0.119
17     B        2  0.126
18     C        2  0.127
19     D        2  0.108
20     E        2  0.109
21     F        2  0.109
22     G        2  0.114
23     H        2  0.107
24     A        3  0.137
25     B        3  0.127
26     C        3  0.123
27     D        3  0.111
28     E        3  0.109
29     F        3  0.111
..   ...      ...    ...
66     C        8  0.122
67     D        8  0.110
68     E        8  0.109
69     F        8  0.110
70     G        8  0.107
71     H        8  0.105
72     A        9  0.127
73     B        9  0.127
74     C        9  0.131
75     D        9  0.111
76     E        9  0.112
77     F        9  0.107
78     G        9  0.107
79     H        9  0.106
80     A       10  0.132
81     B       10  0.126
82     C       10  0.122
83     D       10  0.113
84     E       10  0.108
85     F       10  0.111
86     G       10  0.118
87     H       10  0.102
88     A       11  0.091
89     B       11  0.100
90     C       11  0.091
91     D       11  0.086
92     E       11  0.086
93     F       11  0.085
94     G       11  0.085
95     H       11  0.084

[96 rows x 3 columns]